// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

// Defines values for ComponentAnalysisParamsProviders.
const (
	ComponentAnalysisParamsProvidersSnyk     ComponentAnalysisParamsProviders = "snyk"
	ComponentAnalysisParamsProvidersTidelift ComponentAnalysisParamsProviders = "tidelift"
)

// Defines values for ComponentAnalysisParamsPkgManager.
const (
	ComponentAnalysisParamsPkgManagerMaven ComponentAnalysisParamsPkgManager = "maven"
)

// Defines values for DependencyAnalysisParamsProviders.
const (
	DependencyAnalysisParamsProvidersSnyk     DependencyAnalysisParamsProviders = "snyk"
	DependencyAnalysisParamsProvidersTidelift DependencyAnalysisParamsProviders = "tidelift"
)

// Defines values for DependencyAnalysisParamsPkgManager.
const (
	DependencyAnalysisParamsPkgManagerMaven DependencyAnalysisParamsPkgManager = "maven"
)

// ComponentRequest defines model for ComponentRequest.
type ComponentRequest = []PackageRef

// DependencyReport defines model for DependencyReport.
type DependencyReport struct {
	Issues         *[]Issue    `json:"issues,omitempty"`
	Recommendation *PackageRef `json:"recommendation,omitempty"`
	Ref            *PackageRef `json:"ref,omitempty"`

	// SecurityRecommendations Trusted Content recommendations related to identified security vulnerabilities
	SecurityRecommendations *map[string]Recommendation    `json:"securityRecommendations,omitempty"`
	Transitive              *[]TransitiveDependencyReport `json:"transitive,omitempty"`
}

// Issue defines model for Issue.
type Issue struct {
	Cves    *[]string               `json:"cves,omitempty"`
	Id      *string                 `json:"id,omitempty"`
	RawData *map[string]interface{} `json:"rawData,omitempty"`
	Source  *string                 `json:"source,omitempty"`
}

// PackageRef defines model for PackageRef.
type PackageRef struct {
	// Name <groupId>:<artifactId> for Java packages
	Name *string `json:"name,omitempty"`

	// Version Package version
	Version *string `json:"version,omitempty"`
}

// Recommendation defines model for Recommendation.
type Recommendation struct {
	IssueRef      *string     `json:"issueRef,omitempty"`
	MavenPackage  *PackageRef `json:"mavenPackage,omitempty"`
	ProductStatus *string     `json:"productStatus,omitempty"`
}

// TransitiveDependencyReport defines model for TransitiveDependencyReport.
type TransitiveDependencyReport struct {
	Issues                  *[]Issue                   `json:"issues,omitempty"`
	Ref                     *PackageRef                `json:"ref,omitempty"`
	SecurityRecommendations *map[string]Recommendation `json:"securityRecommendations,omitempty"`
}

// ComponentAnalysisParams defines parameters for ComponentAnalysis.
type ComponentAnalysisParams struct {
	// Providers List of vulnerability providers to get the report from
	Providers *ComponentAnalysisParamsProviders `form:"providers,omitempty" json:"providers,omitempty"`
}

// ComponentAnalysisParamsProviders defines parameters for ComponentAnalysis.
type ComponentAnalysisParamsProviders string

// ComponentAnalysisParamsPkgManager defines parameters for ComponentAnalysis.
type ComponentAnalysisParamsPkgManager string

// DependencyAnalysisParams defines parameters for DependencyAnalysis.
type DependencyAnalysisParams struct {
	// Providers List of vulnerability providers to get the report from
	Providers *DependencyAnalysisParamsProviders `form:"providers,omitempty" json:"providers,omitempty"`
}

// DependencyAnalysisParamsProviders defines parameters for DependencyAnalysis.
type DependencyAnalysisParamsProviders string

// DependencyAnalysisParamsPkgManager defines parameters for DependencyAnalysis.
type DependencyAnalysisParamsPkgManager string

// ComponentAnalysisJSONRequestBody defines body for ComponentAnalysis for application/json ContentType.
type ComponentAnalysisJSONRequestBody = ComponentRequest
